#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_music.py - generate a copyright-free music bed for a brand film.

WHY THIS IS COPYRIGHT-FREE
--------------------------
There is no music model here and no music API. Every sample is SYNTHESISED FROM
SCRATCH out of music theory: a key, a mode, a chord progression, and additive
synthesis voices built from sine partials. Nothing is sampled, nothing is looped
from a library, and no model trained on recorded music is involved at any point.
The output is a mathematical function of (mood, key, mode, bpm, seed, duration).
That is what makes it genuinely clearable -- the person who runs this owns the
result outright, with no licence, no attribution and no rights-holder anywhere.

WHAT IT IS NOT
--------------
This is an UNDERSCORE BED, not a produced track. There are no real instruments,
no performance, no drummer and no arrangement beyond four voices moving through
a chord progression. It is designed to sit *underneath* narration and give a
film a floor -- which is exactly what a corporate film needs and roughly all it
needs. Put it in front of an audience on its own and it will sound like what it
is: a tasteful synth pad. If a film needs a hook, a melody someone hums, or live
players, licence a real track. This will not get you there and pretending
otherwise wastes a client's time.

HOW IT WORKS
------------
44.1 kHz stereo, numpy, written with the stdlib ``wave`` module, mastered with
ffmpeg ``loudnorm``.

  voices    pad   5 harmonics, plus two copies detuned +/-7 cents, slow vibrato
            bell  inharmonic partials at 1 / 2.76 / 5.4 with exponential decay
            sub   fundamental + octave (+ a trace of the twelfth)
            perc  soft kick from a pitch-swept sine, brushes from filtered noise
  envelope  per-note ADSR, raised-cosine attack on the pad
  space     reverb by FFT convolution with an exponentially-decaying seeded
            noise burst; Haas widening (one channel delayed ~220 samples)
  tone      zero-phase spectral shaping: 28 Hz high-pass, high shelf, gentle
            low-pass, so the bed stays under narration instead of fighting it
  form      a real arc -- intro / build / hold / outro -- not four bars looped

Usage:
    make_music.py --duration 30 --mood confident --out bed.wav --json
    make_music.py --duration 45 --brand example --out bed.wav --stems
    make_music.py --duration 20 --key D --mode dorian --bpm 72 --out bed.m4a
    make_music.py --list-moods

Every run writes a sidecar ``<out>.music.json`` describing exactly what was
played, so a bed can be regenerated byte-for-byte or explained to a client.
"""

from __future__ import absolute_import, division

import argparse
import json
import math
import os
import shutil
import subprocess
import sys
import wave

try:
    import numpy as np
except ImportError:  # pragma: no cover - numpy is a hard dependency
    sys.stderr.write(
        "make_music.py needs numpy.\n"
        "  ~/.cache/brand-studio/venv/bin/python -m pip install numpy\n")
    raise SystemExit(2)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import brandlib  # noqa: E402


# ---------------------------------------------------------------------------
# constants
# ---------------------------------------------------------------------------

SR = 44100
CHANNELS = 2

#: Seconds of silence rendered past the requested duration so the final chord's
#: release and the reverb tail exist before the buffer is cut to length.
TAIL_SEC = 4.0

#: Ceiling the pre-master is peak-normalised to, leaving loudnorm headroom.
PREMASTER_PEAK_DBFS = -3.0

#: True-peak ceiling for the mastered bed. Matches build_video.py's
#: LOUDNORM_TP_MUSIC so a bed does not get squashed twice in the film mix.
TARGET_TRUE_PEAK_DB = -2.0

#: Loudness range passed to loudnorm. A bed is meant to be flat.
LOUDNORM_LRA = 11.0

#: Haas delay on the right channel of the pad and arpeggio, in samples (~5 ms).
HAAS_SAMPLES = 220

#: Mid/side width applied after the Haas delay, for mono compatibility.
STEREO_WIDTH = 0.72

DEFAULT_TARGET_LUFS = -23.0
DEFAULT_FADE_IN = 1.2
DEFAULT_FADE_OUT = 2.0
DEFAULT_SEED = 7

NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
FLAT_NAMES = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]
NOTE_ALIASES = {
    "DB": "C#", "EB": "D#", "GB": "F#", "AB": "G#", "BB": "A#",
    "E#": "F", "B#": "C", "FB": "E", "CB": "B",
}

#: Tonics conventionally written with flats, so an F major bed reads "F Bb Dm C"
#: rather than the technically-equivalent-but-wrong-looking "F A# Dm C".
FLAT_TONICS_MAJOR = frozenset((5, 10, 3, 8, 1))          # F Bb Eb Ab Db
FLAT_TONICS_MINOR = frozenset((2, 7, 0, 5, 10, 3, 8))    # Dm Gm Cm Fm Bbm Ebm Abm

#: Scale degrees in semitones.
MODES = {
    "minor": (0, 2, 3, 5, 7, 8, 10),      # aeolian
    "major": (0, 2, 4, 5, 7, 9, 11),      # ionian
    "dorian": (0, 2, 3, 5, 7, 9, 10),
    "lydian": (0, 2, 4, 6, 7, 9, 11),
}

ROMAN = ("I", "II", "III", "IV", "V", "VI", "VII")


# ---------------------------------------------------------------------------
# MOOD PRESETS
# ---------------------------------------------------------------------------
# Every mood is a complete set of musical decisions. Nothing here is decoration:
# mode and progression set the emotional colour, bpm sets the pulse, the voice
# levels set what the bed is made of, arpDensity sets how busy it is, reverb sets
# how far away it sounds, and cutoff/shelf set how much room it leaves for a
# voice sitting on top of it.
#
#   mode          which scale the chords are drawn from
#   bpm           target tempo; the real tempo is nudged to land bars on duration
#   key           default tonic (overridable with --key)
#   degrees       the 4-bar progression, as 0-indexed scale degrees
#   levels        linear mix gain per voice before mastering
#   arpDensity    fraction of the 8 eighth-note slots per bar the bell plays
#   arpOctaves    how far the arpeggio spreads above the chord
#   reverbSec     RT60 of the convolution reverb
#   reverbMix     wet fraction per voice (bass stays dry, bells go furthest back)
#   cutoffHz      low-pass corner; lower = more room for narration
#   shelfDb       high-shelf trim above ~2 kHz
#   detuneCents   pad detune spread
#   vibratoHz/Depth  slow pitch movement so the pad is not static
#   perc          None | "brush" | "brush+kick"

MOODS = {
    "confident": {
        "mode": "minor", "bpm": 84, "key": "A", "degrees": [0, 5, 2, 6],
        "levels": {"pad": 0.55, "sub": 0.25, "arp": 0.20, "perc": 0.115},
        "arpDensity": 0.45, "arpOctaves": 2,
        "reverbSec": 1.9,
        "reverbMix": {"pad": 0.28, "sub": 0.04, "arp": 0.34, "perc": 0.13},
        "cutoffHz": 3200.0, "shelfDb": -4.5,
        "detuneCents": 7.0, "vibratoHz": 0.50, "vibratoDepth": 0.0030,
        "perc": "brush+kick",
        "blurb": "i-VI-III-VII in a minor key at a walking tempo. Forward-moving "
                 "and self-assured rather than sentimental. The house default.",
    },
    "calm": {
        "mode": "dorian", "bpm": 66, "key": "D", "degrees": [0, 3, 6, 0],
        "levels": {"pad": 0.62, "sub": 0.22, "arp": 0.15, "perc": 0.0},
        "arpDensity": 0.26, "arpOctaves": 2,
        "reverbSec": 2.8,
        "reverbMix": {"pad": 0.38, "sub": 0.05, "arp": 0.44, "perc": 0.0},
        "cutoffHz": 2500.0, "shelfDb": -6.0,
        "detuneCents": 6.0, "vibratoHz": 0.33, "vibratoDepth": 0.0026,
        "perc": None,
        "blurb": "Dorian, slow, no percussion, long reverb. For reflective "
                 "openings and anything narrated quietly.",
    },
    "urgent": {
        "mode": "minor", "bpm": 104, "key": "E", "degrees": [0, 6, 5, 4],
        "levels": {"pad": 0.46, "sub": 0.28, "arp": 0.26, "perc": 0.17},
        "arpDensity": 0.68, "arpOctaves": 2,
        "reverbSec": 1.3,
        "reverbMix": {"pad": 0.20, "sub": 0.03, "arp": 0.24, "perc": 0.10},
        "cutoffHz": 3800.0, "shelfDb": -3.0,
        "detuneCents": 8.0, "vibratoHz": 0.62, "vibratoDepth": 0.0032,
        "perc": "brush+kick",
        "blurb": "i-VII-VI-v, faster, drier, busier arpeggio. Pressure without "
                 "drama. Use for a problem beat, not for a whole film.",
    },
    "warm": {
        "mode": "major", "bpm": 74, "key": "F", "degrees": [0, 3, 5, 4],
        "levels": {"pad": 0.60, "sub": 0.23, "arp": 0.17, "perc": 0.07},
        "arpDensity": 0.32, "arpOctaves": 2,
        "reverbSec": 2.3,
        "reverbMix": {"pad": 0.32, "sub": 0.04, "arp": 0.38, "perc": 0.12},
        "cutoffHz": 2900.0, "shelfDb": -5.0,
        "detuneCents": 6.0, "vibratoHz": 0.40, "vibratoDepth": 0.0028,
        "perc": "brush",
        "blurb": "I-IV-vi-V in major, brushes only. Human and unhurried. "
                 "For people-led stories and culture films.",
    },
    "neutral": {
        "mode": "minor", "bpm": 80, "key": "A", "degrees": [0, 2, 5, 6],
        "levels": {"pad": 0.54, "sub": 0.24, "arp": 0.16, "perc": 0.08},
        "arpDensity": 0.34, "arpOctaves": 2,
        "reverbSec": 1.8,
        "reverbMix": {"pad": 0.26, "sub": 0.04, "arp": 0.30, "perc": 0.12},
        "cutoffHz": 3000.0, "shelfDb": -5.0,
        "detuneCents": 6.5, "vibratoHz": 0.45, "vibratoDepth": 0.0026,
        "perc": "brush",
        "blurb": "i-III-VI-VII, deliberately unopinionated. The safe choice when "
                 "the narration is dense and the music must disappear.",
    },
    "uplifting": {
        "mode": "major", "bpm": 96, "key": "D", "degrees": [0, 4, 5, 3],
        "levels": {"pad": 0.52, "sub": 0.24, "arp": 0.25, "perc": 0.14},
        "arpDensity": 0.58, "arpOctaves": 3,
        "reverbSec": 2.0,
        "reverbMix": {"pad": 0.28, "sub": 0.04, "arp": 0.36, "perc": 0.12},
        "cutoffHz": 3600.0, "shelfDb": -3.5,
        "detuneCents": 7.0, "vibratoHz": 0.55, "vibratoDepth": 0.0030,
        "perc": "brush+kick",
        "blurb": "I-V-vi-IV in major, brighter and busier. For an outcome beat "
                 "or a showreel. Tips into corporate-cheerful if overused.",
    },
}

MOOD_ORDER = ["confident", "calm", "urgent", "warm", "neutral", "uplifting"]

#: Moods the brand profile's own `video.music.mood` strings map onto, so the
#: default comes from the brand rather than from this file's opinion.
BRAND_MOOD_HINTS = {
    "confident": "confident", "assured": "confident", "corporate-modern": "confident",
    "modern": "confident", "professional": "confident", "understated": "neutral",
    "restrained": "neutral", "neutral": "neutral", "minimal": "neutral",
    "calm": "calm", "reflective": "calm", "quiet": "calm", "ambient": "calm",
    "warm": "warm", "human": "warm", "friendly": "warm", "optimistic": "uplifting",
    "uplifting": "uplifting", "energetic": "uplifting", "bright": "uplifting",
    "urgent": "urgent", "driving": "urgent", "tense": "urgent",
}

#: Brand `video.music.avoid` strings that rule a mood out. Only list a veto when
#: the mood really would produce the thing being avoided -- an over-eager veto
#: here silently swaps the brand's stated mood for something blander.
MOOD_VETOES = {
    "uplifting": ("aggressive edm", "epic", "anthemic", "triumphant"),
    "urgent": ("aggressive edm", "dramatic orchestral", "trailer", "tense"),
    "warm": ("sentimental", "saccharine"),
    "calm": ("ambient drone", "sleepy"),
    "confident": (),
    "neutral": (),
}


# ---------------------------------------------------------------------------
# SECTION ARRANGEMENT
# ---------------------------------------------------------------------------
# What plays during each section of the arc. "late" means the element enters
# halfway through that section, which is how the bed grows instead of looping.

SECTIONS = {
    "intro": {"level": 0.84, "pad": True, "sub": False, "arp": False,
              "perc": False, "taper": False, "arpScale": 1.0,
              "note": "pad alone, establishing the key"},
    "build": {"level": 0.92, "pad": True, "sub": "late", "arp": "late",
              "perc": "late", "taper": False, "arpScale": 0.8,
              "note": "sub enters, then the arpeggio"},
    "hold": {"level": 1.00, "pad": True, "sub": True, "arp": True,
             "perc": True, "taper": False, "arpScale": 1.0,
             "note": "full arrangement under the body of the narration"},
    "lift": {"level": 1.06, "pad": True, "sub": True, "arp": True,
             "perc": True, "taper": False, "arpScale": 1.35,
             "note": "busier arpeggio, brighter; for a proof or outcome beat"},
    "break": {"level": 0.84, "pad": True, "sub": False, "arp": False,
              "perc": False, "taper": False, "arpScale": 1.0,
              "note": "everything drops but the pad; a breath"},
    "outro": {"level": 0.95, "pad": True, "sub": True, "arp": True,
              "perc": True, "taper": True, "arpScale": 0.7,
              "note": "elements fall away, resolving to the root on the last bar"},
}

SECTION_WEIGHT = {"intro": 1.2, "build": 2.0, "hold": 3.0,
                  "lift": 1.5, "break": 1.0, "outro": 2.0}

#: Order sections get dropped in when the piece is too short to hold them all.
SECTION_DROP_ORDER = ["break", "lift", "build", "hold", "intro", "outro"]

DEFAULT_STRUCTURE = ["intro", "build", "hold", "outro"]


class MusicError(Exception):
    """Anything that should stop the run with an actionable message."""


# ---------------------------------------------------------------------------
# music theory
# ---------------------------------------------------------------------------

def note_to_pc(name):
    """'A' / 'Bb' / 'F#' -> pitch class 0..11."""
    raw = str(name).strip().replace("♯", "#").replace("♭", "b")
    key = raw.upper()
    if key in NOTE_ALIASES:
        key = NOTE_ALIASES[key]
    if key in NOTE_NAMES:
        return NOTE_NAMES.index(key)
    raise MusicError(
        "unknown key %r. Use one of: %s (flats accepted: Bb, Eb, Ab, Db, Gb)"
        % (name, ", ".join(NOTE_NAMES)))


def midi_to_freq(midi):
    return 440.0 * (2.0 ** ((float(midi) - 69.0) / 12.0))


def triad(scale, degree):
    """Semitone offsets of the diatonic triad rooted on ``degree``."""
    n = len(scale)
    out = []
    for step in (0, 2, 4):
        idx = degree + step
        out.append(scale[idx % n] + 12 * (idx // n))
    return out


def triad_quality(intervals):
    third = intervals[1] - intervals[0]
    fifth = intervals[2] - intervals[0]
    if third == 3 and fifth == 7:
        return "min"
    if third == 4 and fifth == 7:
        return "maj"
    if third == 3 and fifth == 6:
        return "dim"
    if third == 4 and fifth == 8:
        return "aug"
    return "maj" if third >= 4 else "min"


def roman_numeral(scale, degree):
    """Roman numeral relative to the *mode's own* scale.

    In A minor that gives i - VI - III - VII for Am F C G, which is how a
    musician would write it, rather than the parallel-major i - bVI - bIII - bVII.
    """
    quality = triad_quality(triad(scale, degree))
    base = ROMAN[degree % 7]
    if quality in ("min", "dim"):
        base = base.lower()
    if quality == "dim":
        base += "°"
    elif quality == "aug":
        base += "+"
    return base


def prefers_flats(tonic_pc, mode_name, raw_key=None):
    """Whether to spell this key with flats. Honours what the user typed."""
    if raw_key:
        text = str(raw_key).strip().replace("♭", "b").replace("♯", "#")
        if len(text) > 1 and text[1] == "b":
            return True
        if len(text) > 1 and text[1] == "#":
            return False
    if mode_name in ("major", "lydian"):
        return tonic_pc in FLAT_TONICS_MAJOR
    return tonic_pc in FLAT_TONICS_MINOR


def spell(pitch_class, flats):
    return (FLAT_NAMES if flats else NOTE_NAMES)[pitch_class % 12]


def chord_name(tonic_pc, scale, degree, flats=False):
    root_pc = (tonic_pc + scale[degree % len(scale)]) % 12
    quality = triad_quality(triad(scale, degree))
    suffix = {"min": "m", "maj": "", "dim": "dim", "aug": "aug"}[quality]
    return spell(root_pc, flats) + suffix


def sanitise_degrees(scale, degrees):
    """Swap out diminished/augmented triads a mode override can introduce.

    Each mood's progression is chosen for its own mode. Forcing a different mode
    with --mode can land a degree on a diminished triad -- vii° in major, #iv° in
    lydian -- which is unstable and reads as a mistake under narration. Dropping
    that degree a third lands on a consonant chord in every supported mode.
    Returns (degrees, substitutions).
    """
    out = []
    swaps = []
    for degree in degrees:
        quality = triad_quality(triad(scale, degree))
        if quality in ("dim", "aug"):
            replacement = (degree - 2) % len(scale)
            swaps.append({"from": ROMAN[degree % 7], "to": ROMAN[replacement % 7],
                          "why": "%s triad is unstable under narration" % quality})
            out.append(replacement)
        else:
            out.append(degree)
    return out, swaps


def voiced_chord(base_midi, tonic_pc, scale, degree):
    """Absolute MIDI notes for the triad, inverted to stay near ``base_midi``.

    Rooting every chord at the same octave makes the progression leap around;
    folding roots above the tritone down an octave gives the smooth, mostly
    stepwise motion a bed wants.
    """
    intervals = triad(scale, degree)
    offset = intervals[0] % 12
    if offset > 6:
        offset -= 12
    root = base_midi + tonic_pc + offset
    return [root, root + (intervals[1] - intervals[0]),
            root + (intervals[2] - intervals[0])]


# ---------------------------------------------------------------------------
# synthesis primitives
# ---------------------------------------------------------------------------

def adsr(n, attack, decay, sustain, release, smooth_attack=True):
    """Per-note amplitude envelope of ``n`` samples."""
    env = np.zeros(n, dtype=np.float64)
    if n <= 0:
        return env
    na = min(int(round(attack * SR)), n)
    nd = min(int(round(decay * SR)), n - na)
    nr = min(int(round(release * SR)), n - na - nd)
    ns = n - na - nd - nr
    i = 0
    if na:
        ramp = np.linspace(0.0, 1.0, na, endpoint=False)
        env[:na] = 0.5 - 0.5 * np.cos(np.pi * ramp) if smooth_attack else ramp
        i = na
    if nd:
        env[i:i + nd] = np.linspace(1.0, sustain, nd, endpoint=False)
        i += nd
    if ns:
        env[i:i + ns] = sustain
        i += ns
    if nr:
        tail = np.linspace(1.0, 0.0, nr, endpoint=True)
        env[i:i + nr] = sustain * (tail ** 1.6)
    return env


def voice_pad(freq, n, phases, detune_cents, vib_hz, vib_depth):
    """Five harmonics, three detuned copies, slow shared vibrato."""
    t = np.arange(n, dtype=np.float64) / SR
    out = np.zeros(n, dtype=np.float64)
    harmonics = ((1, 1.00), (2, 0.42), (3, 0.21), (4, 0.11), (5, 0.065))
    idx = 0
    for cents in (0.0, detune_cents, -detune_cents):
        f0 = freq * (2.0 ** (cents / 1200.0))
        # frequency-modulation index for a vibrato of +/- vib_depth * f0
        index = (vib_depth * f0) / max(vib_hz, 1e-6)
        vib = index * np.sin(2.0 * np.pi * vib_hz * t + phases[idx % len(phases)])
        idx += 1
        for k, amp in harmonics:
            ph = phases[idx % len(phases)]
            idx += 1
            out += amp * np.sin(2.0 * np.pi * f0 * k * t + k * vib + ph)
    return out / 4.6


def voice_bell(freq, n, phase, decay_sec):
    """Inharmonic partials at 1 / 2.76 / 5.4, each decaying exponentially."""
    t = np.arange(n, dtype=np.float64) / SR
    out = np.zeros(n, dtype=np.float64)
    for ratio, amp, rate in ((1.00, 1.00, 1.0), (2.76, 0.42, 1.9), (5.40, 0.19, 3.1)):
        out += amp * np.exp(-rate * t / max(decay_sec, 1e-3)) * \
            np.sin(2.0 * np.pi * freq * ratio * t + phase * ratio)
    return out / 1.61


def voice_sub(freq, n, phase):
    """Fundamental plus octave, with a trace of the twelfth for definition.

    The octave carries about half the weight of the fundamental. A pure sine
    root reads as rumble on a laptop speaker and as mud in a phone mix; the
    octave is what makes the bass line audible where the film is actually
    watched.
    """
    t = np.arange(n, dtype=np.float64) / SR
    return (0.85 * np.sin(2.0 * np.pi * freq * t + phase)
            + 0.45 * np.sin(2.0 * np.pi * freq * 2.0 * t + phase)
            + 0.08 * np.sin(2.0 * np.pi * freq * 3.0 * t)) / 1.38


def voice_kick(n):
    """Soft kick: a sine swept 110 Hz -> 46 Hz with a short exponential decay."""
    t = np.arange(n, dtype=np.float64) / SR
    freq = 46.0 + 64.0 * np.exp(-t / 0.035)
    phase = 2.0 * np.pi * np.cumsum(freq) / SR
    return np.sin(phase) * np.exp(-t / 0.155)


def voice_brush(n, rng):
    """Brush: white noise tilted upward twice, then an 60 ms decay."""
    x = rng.standard_normal(n)
    for _ in range(2):
        x = x - 0.88 * np.concatenate(([0.0], x[:-1]))
    t = np.arange(n, dtype=np.float64) / SR
    env = np.exp(-t / 0.055)
    fade = min(n, int(0.003 * SR))
    if fade:
        env[:fade] *= np.linspace(0.0, 1.0, fade)
    return x * env * 0.35


# ---------------------------------------------------------------------------
# signal processing
# ---------------------------------------------------------------------------

def _fft_len(n):
    size = 1
    while size < n:
        size <<= 1
    return size


def spectral_shape(x, cutoff_hz, shelf_db, hp_hz=28.0, order=2):
    """Zero-phase tone shaping: high-pass, high shelf, gentle low-pass.

    Done in the frequency domain rather than as an IIR loop because a per-sample
    Python filter over a few million samples is unusably slow, and because a
    zero-phase curve keeps the pad's transients where they were.
    """
    n = x.shape[-1]
    pad = int(0.25 * SR)
    size = _fft_len(n + pad)
    spec = np.fft.rfft(x, size, axis=-1)
    freq = np.fft.rfftfreq(size, 1.0 / SR)
    safe = np.maximum(freq, 1e-6)

    hp = 1.0 / np.sqrt(1.0 + (hp_hz / safe) ** 4)
    lp = 1.0 / np.sqrt(1.0 + (safe / max(cutoff_hz, 50.0)) ** (2 * order))
    shelf_start = 1800.0
    span = np.clip(np.log2(safe / shelf_start) / 2.0, 0.0, 1.0)
    shelf = 10.0 ** ((shelf_db / 20.0) * span)

    curve = hp * lp * shelf
    curve[0] = 0.0
    out = np.fft.irfft(spec * curve, size, axis=-1)
    return out[..., :n]


def fft_convolve(x, h):
    """Convolve ``x`` (n,) with ``h`` (m,), truncated back to n samples."""
    n = x.shape[-1]
    m = h.shape[-1]
    size = _fft_len(n + m)
    y = np.fft.irfft(np.fft.rfft(x, size) * np.fft.rfft(h, size), size)
    return y[:n]


def make_reverb_ir(rng, decay_sec, predelay_ms=22.0):
    """Stereo impulse response: decorrelated noise under an exponential decay."""
    n = max(1, int(SR * decay_sec))
    t = np.arange(n, dtype=np.float64) / SR
    env = np.exp(-6.9 * t / max(decay_sec, 1e-3))
    ir = rng.standard_normal((2, n)) * env
    # a short fade-in stops the burst reading as a click at the reverb onset
    fade = min(n, int(0.006 * SR))
    if fade:
        ir[:, :fade] *= np.linspace(0.0, 1.0, fade)
    pre = int(SR * predelay_ms / 1000.0)
    out = np.zeros((2, n + pre), dtype=np.float64)
    out[:, pre:] = ir
    out = spectral_shape(out, 2600.0, -6.0, hp_hz=90.0)
    norm = np.sqrt(np.sum(out ** 2, axis=1, keepdims=True))
    norm[norm < 1e-12] = 1.0
    return out / norm


def haas(stereo, samples):
    """Delay the right channel by ``samples`` for width. Zero-filled, not rolled."""
    if samples <= 0:
        return stereo
    out = stereo.copy()
    out[1] = np.concatenate((np.zeros(samples), stereo[1][:-samples]))
    return out


def set_width(stereo, width):
    """Mid/side width control.

    Independent per-channel pad phases plus a Haas delay produce a very wide
    image, and a wide image partially cancels when a phone or a LinkedIn player
    sums it to mono. Pulling the side channel back to 0.72 keeps the width
    audible on headphones and keeps the bed intact in mono.
    """
    mid = 0.5 * (stereo[0] + stereo[1])
    side = 0.5 * (stereo[0] - stereo[1]) * width
    return np.vstack((mid + side, mid - side))


def db_to_lin(db):
    return 10.0 ** (float(db) / 20.0)


# ---------------------------------------------------------------------------
# composition
# ---------------------------------------------------------------------------

def plan_bars(duration, bpm):
    """Choose a bar count, then adjust the tempo so bars land exactly on ``duration``.

    Truncating the last phrase to hit a duration is what makes generated music
    sound generated. Nudging the tempo by a percent or two is inaudible.
    """
    bars = int(round(duration * float(bpm) / 240.0))
    bars = max(2, bars)
    bpm_eff = 240.0 * bars / duration
    return bars, bpm_eff


def allocate_sections(structure, bars):
    """Split ``bars`` across the requested sections, at least one bar each."""
    sections = list(structure)
    while len(sections) > bars:
        for name in SECTION_DROP_ORDER:
            if name in sections and len(sections) > bars:
                sections.remove(name)
                break
        else:
            sections = sections[:bars]
    weights = [SECTION_WEIGHT.get(s, 1.0) for s in sections]
    total = sum(weights) or 1.0
    raw = [bars * w / total for w in weights]
    counts = [max(1, int(math.floor(v))) for v in raw]
    # hand the remainder out by largest fractional part, deterministically
    while sum(counts) > bars:
        order = sorted(range(len(counts)), key=lambda i: (-counts[i], i))
        for i in order:
            if counts[i] > 1:
                counts[i] -= 1
                break
        else:
            break
    remainder = bars - sum(counts)
    fracs = sorted(range(len(raw)), key=lambda i: (-(raw[i] - math.floor(raw[i])), i))
    i = 0
    while remainder > 0 and fracs:
        counts[fracs[i % len(fracs)]] += 1
        remainder -= 1
        i += 1
    return sections, counts


def build_bar_plan(sections, counts, degrees, bars):
    """One entry per bar: which chord, which elements are audible, at what level."""
    plan = []
    bar = 0
    for name, count in zip(sections, counts):
        spec = SECTIONS[name]
        for j in range(count):
            half = count // 2
            def on(flag):
                if flag == "late":
                    return j >= half
                return bool(flag)
            elements = {
                "pad": on(spec["pad"]),
                "sub": on(spec["sub"]),
                "arp": on(spec["arp"]),
                "perc": on(spec["perc"]),
            }
            if spec["taper"]:
                # elements fall away towards the end of the outro
                elements["arp"] = j < max(0, count - 2)
                elements["perc"] = j < max(0, count - 2)
                if j == count - 1:
                    elements["sub"] = True
            degree = degrees[bar % len(degrees)]
            if bar == bars - 1:
                degree = 0  # resolve to the root on the final bar
            plan.append({
                "bar": bar,
                "section": name,
                "degree": degree,
                "level": spec["level"],
                "arpScale": spec["arpScale"],
                "elements": elements,
                "isLast": bar == bars - 1,
            })
            bar += 1
    return plan


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def render_stems(preset, tonic_pc, scale, bar_plan, bar_sec, n_total, rng):
    """Render the four dry mono stems. Returns {name: float64 array}."""
    stems = {
        "pad": np.zeros((2, n_total), dtype=np.float64),
        "bass": np.zeros(n_total, dtype=np.float64),
        "arp": np.zeros(n_total, dtype=np.float64),
        "perc": np.zeros(n_total, dtype=np.float64),
    }
    bar_n = int(round(bar_sec * SR))
    pad_phases_l = rng.random(64) * 2.0 * np.pi
    pad_phases_r = rng.random(64) * 2.0 * np.pi
    detune = preset["detuneCents"]
    vib_hz = preset["vibratoHz"]
    vib_depth = preset["vibratoDepth"]

    for entry in bar_plan:
        start = entry["bar"] * bar_n
        degree = entry["degree"]
        level = entry["level"]
        last = entry["isLast"]

        # --- pad -----------------------------------------------------------
        if entry["elements"]["pad"]:
            release = 2.6 if last else 0.9
            note_n = min(n_total - start, bar_n + int(release * SR))
            if note_n > 0:
                env = adsr(note_n,
                           attack=0.55 if entry["section"] == "intro" else 0.30,
                           decay=0.35, sustain=0.88, release=release)
                for midi in voiced_chord(48, tonic_pc, scale, degree):
                    freq = midi_to_freq(midi)
                    left = voice_pad(freq, note_n, pad_phases_l, detune, vib_hz, vib_depth)
                    right = voice_pad(freq, note_n, pad_phases_r, detune, vib_hz, vib_depth)
                    stems["pad"][0, start:start + note_n] += left * env * level
                    stems["pad"][1, start:start + note_n] += right * env * level

        # --- sub -----------------------------------------------------------
        if entry["elements"]["sub"]:
            release = 1.6 if last else 0.45
            note_n = min(n_total - start, bar_n + int(release * SR))
            if note_n > 0:
                env = adsr(note_n, attack=0.06, decay=0.25, sustain=0.85,
                           release=release, smooth_attack=False)
                root_midi = voiced_chord(24, tonic_pc, scale, degree)[0]
                stems["bass"][start:start + note_n] += \
                    voice_sub(midi_to_freq(root_midi), note_n, float(rng.random()) * 6.283) \
                    * env * level

        # --- arpeggio ------------------------------------------------------
        if entry["elements"]["arp"] and not last:
            density = min(0.95, preset["arpDensity"] * entry["arpScale"])
            chord = voiced_chord(72, tonic_pc, scale, degree)
            pool = []
            for octave in range(preset["arpOctaves"]):
                pool.extend([m + 12 * octave for m in chord])
            eighth_n = bar_n // 8
            hits = rng.random(8) < density
            hits[0] = True  # always mark the downbeat so the bar has a shape
            step = 0
            for slot in range(8):
                if not hits[slot]:
                    continue
                pos = start + slot * eighth_n
                decay = 0.85
                note_n = min(n_total - pos, int((decay + 0.35) * SR))
                if note_n <= 0:
                    continue
                midi = pool[step % len(pool)]
                step += 1
                gain = 1.0 if slot % 2 == 0 else 0.62
                stems["arp"][pos:pos + note_n] += voice_bell(
                    midi_to_freq(midi), note_n, float(rng.random()) * 6.283, decay
                ) * gain * level

        # --- percussion ----------------------------------------------------
        style = preset["perc"]
        if entry["elements"]["perc"] and style and not last:
            quarter_n = bar_n // 4
            if "kick" in style:
                for beat in (0, 2):
                    pos = start + beat * quarter_n
                    note_n = min(n_total - pos, int(0.45 * SR))
                    if note_n > 0:
                        stems["perc"][pos:pos + note_n] += voice_kick(note_n) * level
            eighth_n = bar_n // 8
            for slot in (1, 3, 5, 7):
                if rng.random() > 0.72:
                    continue
                pos = start + slot * eighth_n
                note_n = min(n_total - pos, int(0.28 * SR))
                if note_n > 0:
                    stems["perc"][pos:pos + note_n] += \
                        voice_brush(note_n, rng) * level * 0.55
    return stems


def process_stem(name, mono_or_stereo, preset, ir):
    """Tone-shape, reverb and widen one stem. Returns a (2, n) array."""
    if mono_or_stereo.ndim == 1:
        stereo = np.vstack((mono_or_stereo, mono_or_stereo))
    else:
        stereo = mono_or_stereo

    cutoff, shelf, high_pass = preset["cutoffHz"], preset["shelfDb"], 28.0
    if name == "bass":
        # the sub has no business above 400 Hz, and nothing below 40 Hz survives
        # a laptop speaker while it does eat headroom
        cutoff, shelf, high_pass = 420.0, -12.0, 40.0
    elif name == "perc":
        cutoff, shelf, high_pass = 6200.0, -2.0, 60.0   # brushes keep some air
    elif name == "pad":
        high_pass = 55.0                                # leave the bottom to the sub
    stereo = spectral_shape(stereo, cutoff, shelf, hp_hz=high_pass)

    wet_amount = preset["reverbMix"].get(
        {"pad": "pad", "bass": "sub", "arp": "arp", "perc": "perc"}[name], 0.0)
    if wet_amount > 0.0:
        wet = np.vstack((fft_convolve(stereo[0], ir[0]),
                         fft_convolve(stereo[1], ir[1])))
        stereo = (1.0 - wet_amount) * stereo + wet_amount * wet

    if name in ("pad", "arp"):
        stereo = set_width(haas(stereo, HAAS_SAMPLES), STEREO_WIDTH)
    return stereo


def apply_fades(buf, fade_in, fade_out):
    n = buf.shape[-1]
    ni = min(n, int(round(fade_in * SR)))
    no = min(n, int(round(fade_out * SR)))
    if ni > 0:
        ramp = np.linspace(0.0, 1.0, ni, endpoint=False)
        buf[:, :ni] *= (0.5 - 0.5 * np.cos(np.pi * ramp))
    if no > 0:
        ramp = np.linspace(0.0, 1.0, no, endpoint=True)
        buf[:, n - no:] *= (0.5 + 0.5 * np.cos(np.pi * ramp))
    return buf


def write_wav(path, stereo):
    """Write a (2, n) float array as 16-bit PCM. No metadata, so it is stable."""
    clipped = np.clip(stereo, -1.0, 1.0)
    interleaved = np.empty(clipped.shape[1] * 2, dtype=np.float64)
    interleaved[0::2] = clipped[0]
    interleaved[1::2] = clipped[1]
    pcm = np.round(interleaved * 32767.0).astype("<i2")
    directory = os.path.dirname(os.path.abspath(path))
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    handle = wave.open(path, "wb")
    try:
        handle.setnchannels(CHANNELS)
        handle.setsampwidth(2)
        handle.setframerate(SR)
        handle.writeframes(pcm.tobytes())
    finally:
        handle.close()


# ---------------------------------------------------------------------------
# ffmpeg
# ---------------------------------------------------------------------------

def which(name):
    found = shutil.which(name)
    if not found:
        raise MusicError(
            "%s is not on PATH. Install it (brew install ffmpeg) and retry." % name)
    return found


def run(cmd, label, timeout=600):
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                          timeout=timeout)
    if proc.returncode != 0:
        tail = proc.stderr.decode("utf-8", "replace").strip().splitlines()[-12:]
        raise MusicError("%s failed (exit %d):\n  %s"
                         % (label, proc.returncode, "\n  ".join(tail)))
    return proc


def measure_loudness(ffmpeg, path, target_i, target_tp):
    """First loudnorm pass. Returns the measured values as strings, or None."""
    proc = subprocess.run(
        [ffmpeg, "-nostdin", "-hide_banner", "-i", path,
         "-af", "loudnorm=I=%0.2f:TP=%0.2f:LRA=%0.2f:print_format=json"
                % (target_i, target_tp, LOUDNORM_LRA),
         "-f", "null", "-"],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=600)
    text = proc.stderr.decode("utf-8", "replace")
    start = text.rfind("{")
    end = text.rfind("}")
    if start < 0 or end < start:
        return None
    try:
        return json.loads(text[start:end + 1])
    except ValueError:
        return None


def loudnorm_filter(target_i, target_tp, measured):
    """Two-pass (linear) loudnorm when a measurement is available.

    Single-pass loudnorm runs a look-ahead limiter that eats the tail of a short
    bed and moves the duration. The linear second pass is a static gain plus a
    limiter, so the sample count is untouched -- which is what makes the exact
    duration guarantee hold.
    """
    base = "loudnorm=I=%0.2f:TP=%0.2f:LRA=%0.2f" % (target_i, target_tp, LOUDNORM_LRA)
    if not measured:
        return base
    try:
        return (base + ":measured_I=%s:measured_TP=%s:measured_LRA=%s"
                       ":measured_thresh=%s:offset=%s:linear=true:print_format=summary"
                % (measured["input_i"], measured["input_tp"], measured["input_lra"],
                   measured["input_thresh"], measured["target_offset"]))
    except KeyError:
        return base


def probe_duration(ffprobe, path):
    proc = subprocess.run(
        [ffprobe, "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", path],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=60)
    try:
        return float(proc.stdout.decode("utf-8", "replace").strip())
    except ValueError:
        return None


def encode(ffmpeg, src, dest, target_i, measured, duration):
    """Master ``src`` to ``dest``, honouring the extension, at exact duration."""
    ext = os.path.splitext(dest)[1].lower()
    cmd = [ffmpeg, "-nostdin", "-hide_banner", "-y",
           "-fflags", "+bitexact", "-i", src,
           "-af", loudnorm_filter(target_i, TARGET_TRUE_PEAK_DB, measured),
           "-ar", str(SR), "-ac", str(CHANNELS),
           "-t", "%.6f" % duration,
           "-map_metadata", "-1"]
    if ext in (".wav", ""):
        cmd += ["-c:a", "pcm_s16le", "-flags:a", "+bitexact", "-bitexact"]
    elif ext in (".m4a", ".mp4", ".aac"):
        cmd += ["-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart"]
    elif ext == ".mp3":
        cmd += ["-c:a", "libmp3lame", "-b:a", "192k"]
    elif ext == ".flac":
        cmd += ["-c:a", "flac"]
    else:
        raise MusicError(
            "unsupported output extension %r. Use .wav (default), .m4a, .mp3 or .flac."
            % ext)
    cmd.append(dest)
    run(cmd, "ffmpeg (master)")


# ---------------------------------------------------------------------------
# brand wiring
# ---------------------------------------------------------------------------

def default_brand_id():
    try:
        brands = brandlib.list_brands()
    except Exception:
        return None
    return brands[0]["id"] if len(brands) == 1 else None


def load_music_config(brand_id):
    """Return (music_dict, brand_id_or_None). Never raises for a missing brand."""
    if not brand_id:
        return {}, None
    brand = brandlib.load_brand(brand_id)
    video = brand.get("video") or {}
    music = video.get("music") or {}
    return music, brand.get("id", brand_id)


def mood_from_brand(music):
    """Pick a default mood consistent with the brand's own mood/avoid arrays."""
    wanted = [str(m).strip().lower() for m in (music.get("mood") or [])]
    avoid = [str(a).strip().lower() for a in (music.get("avoid") or [])]

    scores = dict((m, 0.0) for m in MOOD_ORDER)
    for word in wanted:
        hit = BRAND_MOOD_HINTS.get(word)
        if hit:
            scores[hit] += 2.0
        else:
            for token in word.replace("-", " ").split():
                hit = BRAND_MOOD_HINTS.get(token)
                if hit:
                    scores[hit] += 1.0
    for mood in MOOD_ORDER:
        for veto in MOOD_VETOES.get(mood, ()):
            if any(veto in a for a in avoid):
                scores[mood] -= 5.0
    best = max(MOOD_ORDER, key=lambda m: (scores[m], -MOOD_ORDER.index(m)))
    if scores[best] <= 0.0:
        return "confident", "no usable brand mood hints; falling back to 'confident'"
    reason = "brand video.music.mood %s -> %s" % (json.dumps(wanted), best)
    if avoid:
        reason += "; avoiding %s" % json.dumps(avoid)
    return best, reason


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def parse_args(argv):
    p = argparse.ArgumentParser(
        prog="make_music.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Synthesise a copyright-free music bed from music theory. "
                    "Nothing is sampled and no model is involved, so the output "
                    "is yours outright -- but it is an underscore bed, not a "
                    "produced track.")
    p.add_argument("--duration", type=float, help="length in seconds (exact)")
    p.add_argument("--brand", help="brand id; reads video.music for mood and target LUFS")
    p.add_argument("--mood", choices=MOOD_ORDER,
                   help="default comes from the brand's video.music.mood/avoid")
    p.add_argument("--key", help="tonic, e.g. A, C#, Bb (default: the mood's key)")
    p.add_argument("--mode", choices=sorted(MODES), help="override the mood's mode")
    p.add_argument("--bpm", type=float, help="override the mood's tempo")
    p.add_argument("--seed", type=int, default=DEFAULT_SEED,
                   help="same seed + same parameters = byte-identical file (default 7)")
    p.add_argument("--out", help="output .wav (default), .m4a, .mp3 or .flac")
    p.add_argument("--lufs", type=float,
                   help="integrated loudness target (default: brand video.music.targetLufs)")
    p.add_argument("--structure", default=None,
                   help="comma-separated sections from %s (default %s)"
                        % (",".join(sorted(SECTIONS)), ",".join(DEFAULT_STRUCTURE)))
    p.add_argument("--stems", action="store_true",
                   help="also write pad/bass/arp/perc separately for an editor")
    p.add_argument("--json", action="store_true", help="print the sidecar to stdout")
    p.add_argument("--preview", action="store_true",
                   help="play the result after writing it (afplay/ffplay)")
    p.add_argument("--list-moods", action="store_true",
                   help="print the mood presets and their musical parameters")
    return p.parse_args(argv)


def print_moods():
    for name in MOOD_ORDER:
        preset = MOODS[name]
        scale = MODES[preset["mode"]]
        numerals = [roman_numeral(scale, d) for d in preset["degrees"]]
        pc = note_to_pc(preset["key"])
        flats = prefers_flats(pc, preset["mode"], preset["key"])
        chords = [chord_name(pc, scale, d, flats) for d in preset["degrees"]]
        print("%s" % name)
        print("  %s" % preset["blurb"])
        print("  key/mode      %s %s at %d bpm" % (preset["key"], preset["mode"], preset["bpm"]))
        print("  progression   %s   (%s)" % (" - ".join(numerals), " ".join(chords)))
        print("  voices        pad %.2f  sub %.2f  arp %.2f  perc %.2f (%s)"
              % (preset["levels"]["pad"], preset["levels"]["sub"],
                 preset["levels"]["arp"], preset["levels"]["perc"],
                 preset["perc"] or "none"))
        print("  arpeggio      %.0f%% of eighth-note slots, %d octaves"
              % (preset["arpDensity"] * 100.0, preset["arpOctaves"]))
        print("  space/tone    reverb %.1fs, low-pass %.0f Hz, shelf %.1f dB"
              % (preset["reverbSec"], preset["cutoffHz"], preset["shelfDb"]))
        print("")


def main(argv=None):
    args = parse_args(argv if argv is not None else sys.argv[1:])

    if args.list_moods:
        print_moods()
        return 0

    if args.duration is None:
        raise MusicError("--duration is required (seconds). Try --list-moods to browse presets.")
    duration = float(args.duration)
    if duration < 2.0:
        raise MusicError("--duration must be at least 2 seconds; got %.3f" % duration)
    if duration > 900.0:
        raise MusicError("--duration above 900s is almost certainly a mistake; got %.1f" % duration)

    ffmpeg = which("ffmpeg")
    ffprobe = which("ffprobe")

    brand_id = args.brand or default_brand_id()
    try:
        music_cfg, brand_id = load_music_config(brand_id)
    except brandlib.BrandNotFound as exc:
        raise MusicError(str(exc))

    if args.mood:
        mood, mood_reason = args.mood, "requested with --mood"
    else:
        mood, mood_reason = mood_from_brand(music_cfg)
    preset = dict(MOODS[mood])
    preset["levels"] = dict(preset["levels"])
    preset["reverbMix"] = dict(preset["reverbMix"])

    mode_name = args.mode or preset["mode"]
    scale = MODES[mode_name]
    key_name = args.key or preset["key"]
    tonic_pc = note_to_pc(key_name)
    bpm_requested = float(args.bpm) if args.bpm else float(preset["bpm"])
    if bpm_requested < 30.0 or bpm_requested > 200.0:
        raise MusicError("--bpm must be between 30 and 200; got %.1f" % bpm_requested)

    target_lufs = args.lufs
    if target_lufs is None:
        try:
            target_lufs = float(music_cfg.get("targetLufs", DEFAULT_TARGET_LUFS))
        except (TypeError, ValueError):
            target_lufs = DEFAULT_TARGET_LUFS

    def _fade(key, fallback):
        try:
            value = float(music_cfg.get(key, fallback))
        except (TypeError, ValueError):
            return fallback
        return value if value >= 0.0 else fallback
    fade_in = min(_fade("fadeInSec", DEFAULT_FADE_IN), duration * 0.4)
    fade_out = min(_fade("fadeOutSec", DEFAULT_FADE_OUT), duration * 0.5)

    structure = DEFAULT_STRUCTURE
    if args.structure:
        structure = [s.strip().lower() for s in args.structure.split(",") if s.strip()]
        unknown = [s for s in structure if s not in SECTIONS]
        if unknown:
            raise MusicError("unknown structure section(s) %s. Known: %s"
                             % (", ".join(unknown), ", ".join(sorted(SECTIONS))))
        if not structure:
            raise MusicError("--structure was empty")

    out = args.out or "bed.wav"
    out = os.path.abspath(out)

    # ---- compose ---------------------------------------------------------
    degrees, degree_swaps = sanitise_degrees(scale, preset["degrees"])
    preset["degrees"] = degrees

    bars, bpm_eff = plan_bars(duration, bpm_requested)
    bar_sec = duration / bars
    sections, counts = allocate_sections(structure, bars)
    bar_plan = build_bar_plan(sections, counts, degrees, bars)

    rng = np.random.default_rng(int(args.seed))
    n_samples = int(round(duration * SR))
    n_total = n_samples + int(TAIL_SEC * SR)

    stems = render_stems(preset, tonic_pc, scale, bar_plan, bar_sec, n_total, rng)
    ir = make_reverb_ir(rng, preset["reverbSec"])

    processed = {}
    for name in ("pad", "bass", "arp", "perc"):
        processed[name] = process_stem(name, stems[name], preset, ir)[:, :n_samples]
        del stems[name]

    mix = np.zeros((2, n_samples), dtype=np.float64)
    for buf in processed.values():
        mix += buf

    peak = float(np.max(np.abs(mix)))
    gain = db_to_lin(PREMASTER_PEAK_DBFS) / peak if peak > 1e-9 else 1.0
    mix *= gain
    apply_fades(mix, fade_in, fade_out)

    # ---- master ----------------------------------------------------------
    work = os.path.join(os.path.expanduser("~"), ".cache", "brand-studio", "tmp")
    if not os.path.isdir(work):
        os.makedirs(work)
    premaster = os.path.join(work, "make_music_premaster.wav")
    write_wav(premaster, mix)

    measured = measure_loudness(ffmpeg, premaster, target_lufs, TARGET_TRUE_PEAK_DB)
    encode(ffmpeg, premaster, out, target_lufs, measured, duration)

    stem_paths = {}
    if args.stems:
        # The same static gain goes on every stem, so the stems sum back to the
        # master and a human can rebalance them without re-levelling anything.
        stem_gain_db = 0.0
        if measured:
            try:
                stem_gain_db = min(
                    target_lufs - float(measured["input_i"]),
                    TARGET_TRUE_PEAK_DB - float(measured["input_tp"]))
            except (KeyError, ValueError):
                stem_gain_db = 0.0
        base, ext = os.path.splitext(out)
        for name in ("pad", "bass", "arp", "perc"):
            buf = processed[name] * gain
            apply_fades(buf, fade_in, fade_out)
            raw = os.path.join(work, "make_music_stem_%s.wav" % name)
            write_wav(raw, buf * db_to_lin(stem_gain_db))
            dest = "%s.%s%s" % (base, name, ext if ext else ".wav")
            run([ffmpeg, "-nostdin", "-hide_banner", "-y", "-fflags", "+bitexact",
                 "-i", raw, "-t", "%.6f" % duration, "-map_metadata", "-1",
                 "-c:a", "pcm_s16le", "-flags:a", "+bitexact", "-bitexact",
                 os.path.splitext(dest)[0] + ".wav"],
                "ffmpeg (stem %s)" % name)
            stem_paths[name] = os.path.splitext(dest)[0] + ".wav"
            os.remove(raw)
    del processed
    if os.path.isfile(premaster):
        os.remove(premaster)

    # ---- verify ----------------------------------------------------------
    actual = probe_duration(ffprobe, out)
    final = measure_loudness(ffmpeg, out, target_lufs, TARGET_TRUE_PEAK_DB) or {}

    def _f(key):
        try:
            return round(float(final[key]), 2)
        except (KeyError, TypeError, ValueError):
            return None

    flats = prefers_flats(tonic_pc, mode_name, key_name)
    numerals = [roman_numeral(scale, d) for d in preset["degrees"]]
    chords = [chord_name(tonic_pc, scale, d, flats) for d in preset["degrees"]]

    structure_map = []
    cursor = 0
    for name, count in zip(sections, counts):
        entries = bar_plan[cursor:cursor + count]
        active = sorted(set(k for e in entries for k, v in e["elements"].items() if v))
        structure_map.append({
            "section": name,
            "bars": count,
            "startSec": round(cursor * bar_sec, 3),
            "endSec": round((cursor + count) * bar_sec, 3),
            "elements": active,
            "chords": [chord_name(tonic_pc, scale, e["degree"], flats) for e in entries],
            "note": SECTIONS[name]["note"],
        })
        cursor += count

    error_ms = None if actual is None else round(abs(actual - duration) * 1000.0, 1)
    sidecar = {
        "generator": "brand-studio/scripts/make_music.py",
        "copyright": ("Procedurally synthesised from music theory. No samples, no "
                      "loop library and no trained model were used, so the output "
                      "is original and unencumbered. It is an underscore bed, not "
                      "a produced track."),
        "brand": brand_id,
        "mood": mood,
        "moodReason": mood_reason,
        "moodBlurb": preset["blurb"],
        "key": spell(tonic_pc, flats),
        "mode": mode_name,
        "timeSignature": "4/4",
        "bpm": round(bpm_eff, 3),
        "bpmRequested": round(bpm_requested, 3),
        "bpmAdjustedPct": round((bpm_eff / bpm_requested - 1.0) * 100.0, 2),
        "bars": bars,
        "barSeconds": round(bar_sec, 4),
        "progression": {
            "degrees": list(preset["degrees"]),
            "romanNumerals": numerals,
            "chords": chords,
            "asWritten": "%s  (%s)" % (" - ".join(numerals), " ".join(chords)),
            "substitutions": degree_swaps or None,
        },
        "structure": structure_map,
        "seed": int(args.seed),
        "duration": {
            "requestedSec": round(duration, 4),
            "actualSec": None if actual is None else round(actual, 4),
            "errorMs": error_ms,
        },
        "loudness": {
            "targetLufs": round(float(target_lufs), 2),
            "measuredLufs": _f("input_i"),
            "truePeakDb": _f("input_tp"),
            "lra": _f("input_lra"),
            "truePeakCeilingDb": TARGET_TRUE_PEAK_DB,
        },
        "fade": {"inSec": round(fade_in, 3), "outSec": round(fade_out, 3)},
        "synthesis": {
            "sampleRate": SR,
            "channels": CHANNELS,
            "levels": preset["levels"],
            "arpDensity": preset["arpDensity"],
            "arpOctaves": preset["arpOctaves"],
            "percussion": preset["perc"],
            "reverbSec": preset["reverbSec"],
            "reverbMix": preset["reverbMix"],
            "cutoffHz": preset["cutoffHz"],
            "shelfDb": preset["shelfDb"],
            "detuneCents": preset["detuneCents"],
            "vibratoHz": preset["vibratoHz"],
            "haasSamples": HAAS_SAMPLES,
            "stereoWidth": STEREO_WIDTH,
        },
        "files": {"audio": out, "stems": stem_paths or None},
        "command": "make_music.py " + " ".join(argv if argv is not None else sys.argv[1:]),
    }

    sidecar_path = out + ".music.json"
    with open(sidecar_path, "w") as handle:
        json.dump(sidecar, handle, indent=2, sort_keys=False)
        handle.write("\n")
    sidecar["files"]["sidecar"] = sidecar_path

    if args.json:
        print(json.dumps(sidecar, indent=2))
    else:
        print("wrote    %s" % out)
        print("sidecar  %s" % sidecar_path)
        print("mood     %s  (%s)" % (mood, mood_reason))
        print("music    %s %s, %.1f bpm, %d bars x %.3fs, %s"
              % (spell(tonic_pc, flats), mode_name, bpm_eff, bars, bar_sec,
                 sidecar["progression"]["asWritten"]))
        print("form     %s" % " -> ".join("%s(%d)" % (s["section"], s["bars"])
                                          for s in structure_map))
        print("duration %.3fs requested, %.3fs actual (%s ms off)"
              % (duration, actual if actual is not None else float("nan"),
                 "?" if error_ms is None else error_ms))
        print("loudness %s LUFS (target %.1f), true peak %s dBTP"
              % (sidecar["loudness"]["measuredLufs"], target_lufs,
                 sidecar["loudness"]["truePeakDb"]))
        for name, path in sorted(stem_paths.items()):
            print("stem     %-5s %s" % (name, path))

    if error_ms is not None and error_ms > 50.0:
        sys.stderr.write(
            "WARNING: duration is %.1f ms off the request; the container "
            "may be padding.\n" % error_ms)

    if args.preview:
        player = shutil.which("afplay") or shutil.which("ffplay")
        if not player:
            sys.stderr.write("no afplay or ffplay on PATH; skipping --preview\n")
        else:
            cmd = [player, out] if player.endswith("afplay") else \
                [player, "-autoexit", "-nodisp", "-loglevel", "error", out]
            subprocess.call(cmd, timeout=duration + 20)

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except MusicError as exc:
        sys.stderr.write("make_music.py: %s\n" % exc)
        sys.exit(2)
    except KeyboardInterrupt:
        sys.stderr.write("\ninterrupted\n")
        sys.exit(130)
